### ISSUE TITLE
[Tracking Issue] next Release

### ISSUE THREAD

**Issue by BernhardAuer** [BernhardAuer/austrian-parliament-data-processing#37]
**fullstack Features**
~~- [ ] searchable speech interruptions (zwischenrufe)~~
~~- [ ] speech interruptions visualizations~~

**Scraper**
~~- [ ] store raw html in DB and re-use if applicable~~
- [x] #48
- [x] add unit tests for speech parser
- [x] #47
- [x] #57
- [ ] #61
~~- [ ] manually update data set~~

**Backend**
~~- [ ] fix technical debts in backend/refactor inconsistencies~~

**Frontend**
- [x] #39
- [x] #40
- [x] #41

~~- [ ] #54~~ blocked, because svelteKit2 feature is needed for proper implementation
~~- [ ] add homepage~~
~~- [ ] add project history page~~
~~- [ ] add contributors page~~
~~- [ ] optimize page loading times~~ postboned, no priority right now
- [x] #52

**DevOps**
- [ ] migrate from windows to linux AZ app service
- [ ] logging infrastructure considerations
- [ ] fully automate data scraping

**Documentation**
- [x] add repo description
- [ ] add readme with general info & contribution / setup help

~~- [ ] downloadable DB snapshot for easy self import to local db~~
~~- [ ] youtube-video: short introduction to project~~

**Comment by BernhardAuer** [comment]
random to-do list:
politicalPartie -> politicalParty
shouting -> interjection

**Comment by BernhardAuer** [comment]
![image](https://github.com/BernhardAuer/austrian-parliament-data-processing/assets/40627756/a59d351f-250b-47b0-b63b-55c780e1e8c2)
