### ISSUE TITLE
speech page enhancements

### ISSUE THREAD

**Issue by BernhardAuer** [BernhardAuer/austrian-parliament-data-processing#40]
**Tasks**
- general tasks
  - [x] fix: do not show empty chat-bubbles with time only
  - [x] desktop: smaller width of chat bubbles (better reading xp)
  - [x] add link to original doc/video and cc remark (check if cc remark is even neccessary...)
  - [x] website title/page title: GP, meetingNr, Topic, speaker Name
  - [x] url schema change: instead of ascending number use speaker name and optional numbering (for multiple speeches by same person

- chat enhancements
  - [x] speaker chat on left side only
  - [x] other chats on right side only
  - [x] fixed color for main speaker (primary color?)
  - [x] fixed color for president of parliament
  - [x] different colors for remaining speakers (but same colors for same speaker on current page)
  - [x] applause activity with emoji
  - [x] shout activity with emoji
  - [x] general/unknown info as info-box
  - [x] further description of speaker shown as small gray text (same as time)
  

- postboned
  ~~- [ ] breadcrumb navigation~~

**Comment by BernhardAuer** [comment]
apparently no CC Remark necessary: 

> Erlaubte Nutzung und Lizenzierung der Daten zu Stenographischen Protokollen
[..] Darüber hinaus sind bei Protokollen auch die Dokumente freie Werke und somit ohne Lizenzierung frei nutzbar. Dies trifft ausschließlich auf die Stenographischen Protokolle der Sitzungen des Nationalrats und des Bundesrats zu.

[see](https://www.parlament.gv.at/recherchieren/open-data/daten-und-lizenz/stenographische-protkolle)

**Comment by BernhardAuer** [comment]
old style: 
![image](https://github.com/BernhardAuer/austrian-parliament-data-processing/assets/40627756/bde246de-9f31-433b-bb17-b890b1fd6668)

**Comment by BernhardAuer** [comment]
"allgemein" not being parsed
![image](https://github.com/BernhardAuer/austrian-parliament-data-processing/assets/40627756/39711de0-841b-4b65-abce-609f1149ac98)

**Comment by BernhardAuer** [comment]
better show this additional info as popup (or maybe as extra info symbol?):
![image](https://github.com/BernhardAuer/austrian-parliament-data-processing/assets/40627756/2a3393e1-91c1-43bc-a63c-5ab4d07ca05d)

**Comment by BernhardAuer** [comment]
todo: fix parsing error ("." only)

todo: only show specific unknown info text (not whole paragraph)

**Comment by BernhardAuer** [comment]
![image](https://github.com/BernhardAuer/austrian-parliament-data-processing/assets/40627756/630e9f67-5ced-448c-9e69-84cff882925e)
http://localhost:5173/wortmeldungen/XXVII/160?thema=Arbeitsmarktservicegesetz+und+Arbeitsmarktpolitik-Finanzierungsgesetz 
http://localhost:5173/wortmeldung/XXVII/160/Arbeitsmarktservicegesetz%20und%20Arbeitsmarktpolitik-Finanzierungsgesetz/4?speaker=Dagmar%20Belakowitsch
