### ISSUE TITLE
refactor speech info parser

### ISSUE THREAD

**Issue by BernhardAuer** [BernhardAuer/austrian-parliament-data-processing#47]
**Tasks**

- [x] rewrite speech info parser as state machine
- [x] check potential wrong entities (see embedded json exported by my custom mongodb aggregation pipeline)
- [x] add tests

**Known Bugs**
~~- [ ]  parsing of names with Mag [.] / MMag [.] / Ing (potential all titles) are not working~~ --> not needed anymore (see https://github.com/BernhardAuer/austrian-parliament-data-processing/issues/47#issuecomment-1866772926)
- [x] Parsing of unknown names is not good enough (see json); e.g.: "reicht Vizekanzler Kogler Hand" 
  - named entity recognition or classic algorithm? Names are probably highlighted somehow in the raw HTML source code ....

**generall discussion**
Raw text parsing only? Or html enriched parsing? --> since when is proper hmtl encoded doc available?

[austrianParliamentaryDataScraping.speechesMetaData-potentialWrongEntityList.json](https://github.com/BernhardAuer/austrian-parliament-data-processing/files/13539773/austrianParliamentaryDataScraping.speechesMetaData-potentialWrongEntityList.json)

**Comment by BernhardAuer** [comment]
parsing of names with Mag [.] / MMag [.] / Ing (potential all titles) are not working -> ok, this does not need to get fixed

It seems that titles before names only gets printed on Entschließungsanträge & co. but not on any potential info items.

should be re-validated later though!
