### ISSUE TITLE
[Tracking Issue] future Release 

### ISSUE THREAD

**Issue by BernhardAuer** [BernhardAuer/austrian-parliament-data-processing#49]
**fullstack Features**
- [ ] searchable speech interruptions (zwischenrufe) 
- [ ] speech interruptions visualizations
- [ ] feedback button

**Scraper**
- [ ] Update scrapy
- [ ] store raw html in DB and re-use if applicable
- [ ] phytify project / refactor scraper (DI, structured logging, ....)

**Backend**
- [ ] upgrade to .net8
- [ ] fix technical debts in backend/refactor inconsistencies

**Frontend**
- [ ] update to svelte 5
- [ ] Migrate to svelteKit 2 [https://kit.svelte.dev/docs/migrating-to-sveltekit-2](url)
- [ ] update tailwind/daisyUI 4
- [ ] SEO optimizations
- [ ] optimize page loading times
- [ ] add homepage
- [ ] add project history page
- [ ] add contributors page
- [ ] scroll up button

**DevOps**

**Documentation**
- [ ] downloadable DB snapshot for easy self import to local db
- [ ] youtube-video: short introduction to project
